zurichat/zc_plugin_youtube_music_video

frontend/public/index.html

I added an H1 to the index to test whether that helps display

index test

---

frontend/src/components/common/button.js

Creates Add and Play Song Buttons with HTML/CSS
Issue: #279

Create Add and Play Button with HTML/CSS issue #279

---

frontend/src/components/common/like.js

issue #268
converted like button to react

Convert Like button to react

---

frontend/src/components/common/chatHeader.js

I converted the HTML and CSS codes for the Chat header to React.Js component. This would help the user to identify the chat section on the app.

Converted ChatHeader to React component issue #259

---

frontend/src/components/common/playlistItem.js
frontend/src/components/common/playlistitem.css

Convert Html to React component #264

---

config/alert.env
frontend/.gitignore
frontend/src/components/common/alert.js

created alert message with html/css/javascript issue #246

created alert message with html/css/javascript issue #246

---

frontend/src/components/common/chatInput.js

This contains the HTML/CSS codes for Chatinput as written by Hobee J

HTML/CSS for ChatInput

---

accounts/views.py

Added comment serializers and views for testing

added comment

---

accounts/models.py

Created a Songs model that stores the individual data of each song gotten from Youtube in the db.
Some the data stored include: the song's title, artiste, album, likes etc.
Endpoint at https://music.zuri.chat
Testing url at https://music.zuri.chat/songs

Created a 'Songs' model issue 274

---

frontend/src/mock-data/songs.js

Created mock data for playlist component
issue: not yet created
author: damkols

Created mock data for playlist component

---

accounts/serializers.py

worked on the song model serializer to create the set of fields based on the Song Model.
dependent on the views and URLs respectively, the live link below would return the JSON format:
https://music.zuri.chat/songs/

Issue #229: setup the song model serializers for the songs endpoint of the music room

---

config/urls.py

Test for [music.zuri.chat](https://music.zuri.chat) endpoints and also test for the Zuri Core Data API.
After which a report was generated using code coverage module. This solves issue #217 and #260 . 
Test report URL : [test report](http://music.zuri.chat/testreport)

Test for music endpoint and DB Save and Retrieve

---

accounts/views.py

Issue #233
Slack Name:- Omotolani12 
worked on the song views of the Song model.
Use the live link below to test:
https://music.zuri.chat/songs/

Ticket 233:- Setup the songs model views for the songs endpoint of the music room

---

config/urls.py

Worked urls for songs models issues #226 
slack name: dev_frank
live link : https://music.zuri.chat/songs/

Worked on urls for song models, issue #226

---

accounts/views.py

Slack Name: Omotolani12
Worked on the Songs views for the songs endpoint of the room
This takes a web request and returns a web response on the frontend
Testing link at https://music.zuri.chat/songs/

setup the song model views for the songs endpoint of the music room

---

accounts/views.py

Test for [music.zuri.chat](https://music.zuri.chat) endpoints and also test for the Zuri Core Data API.
After which a report was generated using code coverage module. This solves issue #217 and #260 .

Endpoint Test And DB test

---

frontend/src/components/chat.js
frontend/src/components/playlist.js

Reverts zurichat/zc_plugin_youtube_music_video#512

Revert "Connect the redux store to appropriate components #491"

---

.gitignore
README.md
frontend/src/App.tsx
frontend/src/components/chat.tsx
frontend/src/components/common/chatHeader.tsx
frontend/src/components/common/chatItem.tsx
frontend/src/components/common/playlistHeader.tsx
frontend/src/components/musicRoom.tsx
frontend/src/components/playlist.tsx
frontend/src/components/roomHeader.tsx
frontend/src/frontendIssues.md
frontend/src/media/chat.svg
frontend/src/media/chatItem.svg
frontend/src/media/close.svg
frontend/src/mock-data/chats.js
frontend/src/store/usersSlice.ts
frontend/yarn.lock

Reverts zurichat/zc_plugin_youtube_music_video#543

Revert "new setup complete: let the party begin!"

---

config/settings.py
frontend/package.json
frontend/src/components/roomHeader.tsx
frontend/yarn.lock
music/utils/data_access.py
music/views.py

Follow instructions [here](https://centrifugal.dev/docs/getting-started/installation) to setup centrifugo and generate config.json

Centrifugo local setup

---

server/client/package.json
server/client/src/components/common/chatInput.tsx
server/client/yarn.lock

An Emoji Picker selector has been integrated into the chat Input section.

Added the Emoji Picker Feature in the chatInput section

---

server/music/urls.py
server/music/views.py

Its endpoint is: http://127.0.0.1:8000/music/api/v1/header-user-count/

Create counter to show the number of times plugin has been accessed

---

server/music/views.py

Endpoint is: http://127.0.0.1:8000/music/api/v1/header-user-count/

Added back the centrifugo_post import

---

server/client/src/components/chat.tsx

Made changes to the Chat component features upon the ChatInput component onFocus or onBlur.

Adjust chat input for mobile responsiveness

---

server/client/src/components/Modals/EnterRoom.js

Modify enter room for responsiveness

Making enter room responsive for mobile

---

server/music/urls.py
server/music/utils/data_access.py
server/music/utils/vet_token.py
server/music/views.py

Endpoint to save new user to room and send data to fe

Display Event when user enters or exits the room

---

.github/workflows/main.yml
server/client/src/components/common/chatInput.tsx

Reverts zurichat/zc_plugin_youtube_music_video#643

Revert "Aligned the emoji picker to position well onClick"

---

server/client/src/types/likeSong.d.ts

playlistitem error fix

---

server/music/views.py

Reverts zurichat/zc_plugin_youtube_music_video#696

Revert "Updated views.py for like songs function"

---

server/client/src/components/common/pasteUrl.tsx
server/client/src/components/common/playlistHeader.tsx

Made the playlist header sticky so as to keep details on the page while scrolling.

Made Playlist Header Sticky

---

server/config/settings.py
server/config/urls.py
server/music/serializers.py
server/music/urls.py
server/music/utils/data_access.py
server/music/views.py

Reverts zurichat/zc_plugin_youtube_music_video#710

Revert "edited sidebar"

---

server/client/src/App.tsx

Reverts zurichat/zc_plugin_youtube_music_video#725

Revert "user info"

---

server/client/src/components/chat.tsx
server/client/src/components/common/chatInput.tsx
server/client/src/components/common/chatItem.tsx

Implemented word wrap for chatInput and chatItem as well as better mobile responsiveness for chat on smaller screens.

Implemented Word Wrap and Better Mobile Responsiveness for Chat

---

server/config/settings.py
server/requirements/base.txt

Reverts zurichat/zc_plugin_youtube_music_video#743

Revert "remove redundant apps."

---

server/client/src/components/common/playlistItem.tsx

Commented out the trim() method in playlistItem.tsx making the page go blank.

identified and commented out the bug making the page go blank

---

server/client/src/components/player.tsx

Make the songs continue playing even when you switch from the music player

Make the songs continue playing even when you switch from the music player

---

server/music/urls.py
server/music/views.py

room url ehn.

---

server/client/src/components/common/filterBar.tsx
server/client/src/components/common/searchBar.tsx

The list of songs are filtered as the user types in the search bar

Song search / filter

---

server/config/settings.py
server/music/functions.py
server/music/models.py
server/music/serializers.py
server/music/urls.py
server/music/views.py

Reverts zurichat/zc_plugin_youtube_music_video#815

Revert "Function updates"

---

server/client/src/App.tsx
server/client/src/app/playerSlice.ts
server/client/src/app/songsSlice.ts
server/client/src/components/common/filterBar.tsx
server/client/src/components/common/likeOptionCount.tsx
server/client/src/components/common/pasteUrl.tsx
server/client/src/components/common/searchBar.tsx
server/client/src/components/common/sortBar.tsx
server/client/src/components/modals/deleteModal.tsx
server/client/src/components/playlist.tsx
server/client/src/components/playlistHeader.tsx
server/client/src/components/searchFilter.tsx
server/client/src/services/eventService.ts
server/client/src/services/httpService.ts
server/client/src/services/logService.ts
server/client/src/services/songService.ts
server/client/src/types.d.ts

This PR integrates all the song endpoints. Now, users can add a song, like a song, delete a song, and also see the list of available songs.

Integrate endpoints for adding, deleting and liking songs

---

server/.pre-commit-config.yaml
server/config/urls.py
server/music/urls.py
server/music/views.py

music isn't showing up on the sidebar. Adjusted some of the parameters and switched the url

minor sidebar fixes

---

server/client/src/app/playerSlice.ts
server/client/src/app/songsSlice.ts
server/client/src/app/uiSlice.ts
server/client/src/components/common/exit.tsx
server/client/src/components/common/labeledSelect.tsx
server/client/src/components/common/like.tsx
server/client/src/components/common/likeOptionCount.tsx
server/client/src/components/common/optionMenu.tsx
server/client/src/components/common/pasteUrl.tsx
server/client/src/components/common/playlistItem.tsx
server/client/src/components/common/select.tsx
server/client/src/components/loader.tsx
server/client/src/components/messageBoard.tsx
server/client/src/components/modals/deleteModal.tsx
server/client/src/components/musicRoom.tsx
server/client/src/components/player.tsx
server/client/src/components/playlist.tsx
server/client/src/components/searchSortFilter/search.tsx
server/client/src/components/searchSortFilter/searchSortFilter.tsx
server/client/src/index.css
server/client/src/utils/idGenerator.ts
server/client/src/utils/metadata.ts

1. Made searchSortFilter mobile responsive
2. Made playlist responsive
3. Made fixes and refactors and cleanups.
4. And others...

Mobile Responsiveness & Pixel Perfection

---

server/music/models.py
server/music/serializers.py
server/music/utils/dataStorage.py
server/music/utils/data_access.py
server/music/views.py

Reverts zurichat/zc_plugin_youtube_music_video#941

Revert "Update staging from dev 7th Dec 21"

---

server/music/models.py
server/music/serializers.py
server/music/utils/dataStorage.py
server/music/utils/data_access.py
server/music/views.py

Reverts zurichat/zc_plugin_youtube_music_video#942

Revert "Update main from dev 7th Dec 21"

---

server/music/serializers.py
server/music/urls.py
server/music/utils/data_access.py
server/music/views.py

Created update comment and room endpoints
Error handling on endpoints
refactored song  and comment delete endpoint
refactored create room endpoint

update and delete endpoint fixes

---

root/src/index.ejs
server/client/src/components/musicRoom.tsx
server/client/src/utils/config.ts

- use plugin header from zuri UI

integrate updated plugin_header from zuri UI

---

server/music/urls.py
server/music/view/songs.py
server/music/view/static.py

Reverts zurichat/zc_plugin_youtube_music_video#958

Revert "Updates from dev branch"

---

server/music/urls.py
server/music/view/songs.py
server/music/view/static.py

Reverts zurichat/zc_plugin_youtube_music_video#959

Revert "Revert "Updates from dev branch""

---

server/music/utils/data_access.py
server/music/view/static.py

Reverts zurichat/zc_plugin_youtube_music_video#961

Revert "Fixes to sidebar room image "
